### PR TITLE
Enforce `deno fmt` formatting

### PR DESCRIPTION
**Pull request by mybearworld**
- Set VSCode to format everything with `deno fmt`
- Format all Markdown files with `deno fmt`
  - These blank lines are necessary because `deno fmt` was annoying and would break it otherwise - Prettier would be better about this but this uses `deno fmt` already
    ```md
    :::warning


    The chat `livechat` is a special chat. It doesn't require you to be a member to
    access it, posts aren't saved to the database, and the chat nor its previous
    posts can be fetched.


    :::
    ```
- Add `deno-fmt-ignore` sections around tables

### CODE REVIEW

**Review by williamhorning — CHANGES_REQUESTED** [review]
looks good aside from the vscode config. id rather we not have editor-specific config in repos though as it just creates a lot of clutter and inconsistency between projects

**Comment by mybearworld** [comment]
> looks good aside from the vscode config. id rather we not have editor-specific config in repos though as it just creates a lot of clutter and inconsistency between projects

That makes it much easier to contribute, though - Prettier would reformat every file any VSCode user (who doesn't only use Deno) edits without it.

If consistency between projects is a priority, Prettier should be used as that's also what's used by Meower Svelte.

**Comment by showierdata9978** [comment]
> > looks good aside from the vscode config. id rather we not have editor-specific config in repos though as it just creates a lot of clutter and inconsistency between projects
> 
> That makes it much easier to contribute, though - Prettier would reformat every file any VSCode user (who doesn't only use Deno) edits without it.
> 
> If consistency between projects is a priority, Prettier should be used as that's also what's used by Meower Svelte.

I agree

**Comment by williamhorning** [comment]
in addition to the stuff below, i also think we should have formatting and linting be a check on every push, see apic for an example workflow

> That makes it much easier to contribute, though - Prettier would reformat every file any VSCode user (who doesn't only use Deno) edits without it.

that's only if you tell it to format your code. vscode config is fine i guess if we 

1) also add the deno plugin as a recommendation (this'll prompt you to install it), and
2) add the same config to apic

> If consistency between projects is a priority, Prettier should be used as that's also what's used by Meower Svelte.

svelte is the exception, not the rule. for our go projects, we're using `go fmt`. for the stuff using deno, we're going with `deno fmt`. for stuff on node, we'll leave those as is until we move them over to deno, which is when we'll switch.

**Comment by mybearworld** [comment]
> in addition to the stuff below, i also think we should have formatting and linting be a check on every push, see apic for an example workflow

👍

> also add the deno plugin as a recommendation (this'll prompt you to install it), and

👍

> svelte is the exception, not the rule. for our go projects, we're using `go fmt`. for the stuff using deno, we're going with `deno fmt`. for stuff on node, we'll leave those as is until we move them over to deno, which is when we'll switch.

`deno fmt` is less mature and supports fewer formats (I couldn't format the YAML config file with it). Prettier is used in every other JS project that has formatting on Meower.

**Review by williamhorning — DISMISSED** [review]

**Comment by mybearworld** [comment]
Just noticed that `deno fmt` does not support frontmatter in Markdown files

image

**Comment by williamhorning** [comment]
> `deno fmt` is less mature and supports fewer formats (I couldn't format the YAML config file with it). Prettier is used in every other JS project that has formatting on Meower.

i'd much rather we not have yet another tool when dealing with formatting, linting, and testing. deno fmt works fine for the majority of stuff we need to work with and change often.

> Just noticed that `deno fmt` does not support frontmatter in Markdown files

if you just have the title set with a markdown heading, it'll be fine

**Review by williamhorning — APPROVED** [review]
:shipit:

**Pull request merged**
