### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by mybearworld**
~~CC BY 4.0 comes pretty close to MIT I think, so I went with that~~

MIT, like most other repos

### CODE REVIEW

**Comment by JoshAtticus** [comment]
everything has to be mit

**Comment by mybearworld** [comment]
Even for repos that aren't really code?

**Comment by mybearworld** [comment]
I suppose http-meower is also released under MIT. I've edited the license

**Review by tnix100 — APPROVED** [review]

**Comment by tnix100** [comment]
I forgot to add this earlier lol, thanks for the PR :)

**Comment by showierdata9978** [comment]
> I suppose http-meower is also released under MIT. I've edited the license

http meower's server is under mit, but all branding is under CC-SA (dr the full clause)

**Pull request merged**
