### PR TITLE
Update authpswd.md to make it clear not to use authpswd

### PR DESCRIPTION
**Pull request by Finley224**
I wrote a client using this to login, it should be more clear that this should not be used.

### CODE REVIEW

**Comment by Finley224** [comment]
let me fix this

**Comment by Finley224** [comment]
"nodeModulesDir": "auto", is breaking it

**Comment by williamhorning** [comment]
> "nodeModulesDir": "auto", is breaking it

please update to the latest deno 2 rc using `deno upgrade --rc`

**Comment by Finley224** [comment]
> > "nodeModulesDir": "auto", is breaking it
> 
> please update to the latest deno 2 rc using `deno upgrade --rc`

ok, let me give that a go

**Comment by Finley224** [comment]
ok. if you re run the checks it should work now.

**Comment by Finley224** [comment]
> ok. if you re run the checks it should work now.

Yep, checks passed.

**Comment by williamhorning** [comment]
alright, despite the checks passing, authpswd isn't completely replaced by the api route. in the majority of cases, you should use the api route and then pass the token to cloudlink using the token query parameter when connecting (with a url like `wss://server.meower.org/?v=1&token=no`, however, without that documented anywhere, just saying "don't use authpswd" is bad.

**Comment by Finley224** [comment]
> alright, despite the checks passing, authpswd isn't completely replaced by the api route. in the majority of cases, you should use the api route and then pass the token to cloudlink using the token query parameter when connecting (with a url like `wss://server.meower.org/?v=1&token=no`, however, without that documented anywhere, just saying "don't use authpswd" is bad.

ok, is there a way It could be worded better?

**Comment by Finley224** [comment]
@williamhorning what about adding a note like, Instead of using authpswd, get a token using the REST API then connect to the web socket with your token "wss://server.meower.org/?v=1&token={your token from api}".

**Comment by williamhorning** [comment]
yes, that'd work

**Comment by Finley224** [comment]
ok, let me add that to the pull request

**Comment by Finley224** [comment]
Ok, I updated it based on your feedback @williamhorning.

**Review by williamhorning — CHANGES_REQUESTED** [review]
please remove package-lock file

**Comment by Finley224** [comment]
@williamhorning done

**Review by williamhorning — APPROVED** [review]

**Pull request merged**
